; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32-wroom

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1

[env:esp32-wroom]
board = esp32dev
build_flags =
    -DDEVICE_PROFILE_NAME=\"ESP32-WROOM-32\"

[env:esp32-c3]
board = esp32-c3-devkitm-1
build_flags =
    -DDEVICE_PROFILE_NAME=\"ESP32-C3-DevKitM-1\"

[env:esp32-c6]
board = esp32-c6-devkitc-1
build_flags =
    -DDEVICE_PROFILE_NAME=\"ESP32-C6-DevKitC-1\"

[env:esp32-s3]
board = esp32-s3-devkitc-1
monitor_port = /dev/ttyACM0
monitor_speed = 115200
extra_scripts =
    pre:scripts/select_s3_port.py
build_flags =
    -DDEVICE_PROFILE_NAME=\"ESP32-S3-DevKitC-1-N8\"
