substitutions:
  device_name: "esp32-ha-kit-c3"
  friendly_name: "ESP32 HA Kit C3"
  dht_pin: "GPIO4"
  pir_pin: "GPIO3"
  relay_pin: "GPIO7"
  heartbeat_pin: "GPIO10"
  sda_pin: "GPIO6"
  scl_pin: "GPIO5"
  oled_address: "0x3C"

packages:
  common: !include common.yaml

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
