substitutions:
  device_name: "esp32-ha-kit-c6"
  friendly_name: "ESP32 HA Kit C6"
  dht_pin: "GPIO2"
  pir_pin: "GPIO3"
  relay_pin: "GPIO7"
  heartbeat_pin: "GPIO18"
  sda_pin: "GPIO6"
  scl_pin: "GPIO10"
  oled_address: "0x3C"

packages:
  common: !include common.yaml

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
